name: Build and install on Ubuntu
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # TODO(PM): libiio will make backwards incompatible changes in v1.0 so
        # consider specifying deb version or using a git submodule
      - name: Build application
        run: |
          sudo apt update
          # Dependencies not available in the official Ubuntu container
          sudo apt install -y cmake git libxml++2.6-dev
          # Dependencies not available in the Github-hosted runner environment
          sudo apt install -y libgtk-3-dev libgtkdatabox-dev libfftw3-dev libcurl4-openssl-dev libjansson-dev libmatio-dev libiio-dev
          mkdir build
          cd build
          mkdir install
          cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..
          make -j$(nproc) install

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-22.04-install-artifacts
          path: build/install
